
server:
  port: 8081


spring:
  datasource:
    #MySQL
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 962464
    url: jdbc:mysql://localhost:3306/demo-quartz?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
